apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: quectosoft-hr-tls
spec:
  secretName: quectosoft-hr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - api.quectosoft.example.com
