apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: quectosoft-hr-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cloud-secrets
    kind: ClusterSecretStore
  target:
    name: quectosoft-hr-secrets
  data:
    - secretKey: AUTH_API_KEYS
      remoteRef:
        key: quectosoft/hr/AUTH_API_KEYS
    - secretKey: WEBHOOK_SECRET
      remoteRef:
        key: quectosoft/hr/WEBHOOK_SECRET
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: quectosoft/hr/OPENAI_API_KEY
