apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quectosoft-hr-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.quectosoft.example.com
      secretName: quectosoft-hr-tls
  rules:
    - host: api.quectosoft.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quectosoft-hr-service
                port:
                  number: 80
