apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quectosoft-hr-servicemonitor
spec:
  selector:
    matchLabels:
      app: quectosoft-hr-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
